### ISSUE TITLE
DisplayObjectContainer 的removechildAt 方法使得runner  WeaponTool出现bug

### ISSUE THREAD

**Issue by iwege** [flashlizi/casualjs#2]
在 DisplayObjectContainer 的86行，对child.stage = null的操作将使得runner的WeaponTool清空自己的stage，会使得第二次的点击出现问题。
目前解决方案是在需要weaponTool的时候再new一个新的（当前使用的），或者去掉这个赋值。

**Comment by flashlizi** [comment]
DisplayObjectContainer.removeChildAt方法删除一个child，必然要把child的stage置空，否则会造成内存泄露的。你做了什么操作使得WeaponTool的stage为空了？一般的，应该是再把WeaponTool实例addChild到舞台上。

**Comment by iwege** [comment]
当点击了塔之后在点击到其他地方，weaponTool.remove();
这个时候会调用this.stage.removeChild(this)的方法。

然后再点击塔的时候，已经实例化之后的weaponTool因为没有stage会导致show的方法当中stage.addChild出问题。

**Comment by flashlizi** [comment]
你可以改造一下weaponTool的remove方法，去掉this.stage.removeChild(this); 改为this.visible = false;
调用show方法的时候，就只要调用this.visible = true，不用再addChild了。

**Comment by iwege** [comment]
这样好像还出现了无法再次显示的问题，先还是使用老的版本先，我每次new一个新的，保证work
