### ISSUE TITLE
how to make Shape respond to mouse event

### ISSUE THREAD

**Issue by jsutil4** [flashlizi/casualjs#4]
我尝试画一个矩形（或任意多边形），然后希望当鼠标在矩形内部点击时，可以做某些操作。
请帮忙看一下下面的代码有什么问题。

var canvas = document.getElementById('canvas'),
    context = canvas.getContext("2d"),
    stage = new Stage(context);

stage.traceMouseTarget = true;

var section1 = new Shape();
section1.graphics.lineStyle(5, "#cccccc");
section1.graphics.drawRect(20,100, 55, 110);
stage.addChild(section1);

section1.onMouseEvent = function(evnet){
    console.log('onMouseEvent');
    console.log(event);
}

**Comment by flashlizi** [comment]
shape.mouseEnabled = true;
形状默认是不接受鼠标事件的。把这个属性打开就可以了。

**Comment by jsutil4** [comment]
你说的方法确实可以。不过我发当鼠标在矩形边框上的时候才会触发事件。在矩形内部并不会触发事件。这样的话，对矩形本身的操作将会受限啊。是不是需要其他的设置？

**Comment by flashlizi** [comment]
如果你的矩形内部是透明的，也就是说内部无像素，那也不会触发事件的。

**Comment by flashlizi** [comment]
你没调用graphics的beginFill等填充方法，所以会造成矩形内部无填充颜色即透明，故不会触发事件。你可以调用beginFill("#ff0",1)或beginBitmapFill等方法填充矩形。
