### ISSUE TITLE
EventManager.js issue

### ISSUE THREAD

**Issue by jsutil4** [flashlizi/casualjs#5]
In EventManager.js Line 79 - Line 99. The logic of removeEventListener is not correct. The variable "empty" is not set correctly.

sample fix:

var lid = EventManager._listeners[listener];
var count = 0, toremove = [];
for(var id in map){
    if (id == lid){
        toreomove.push(id);
    }
    count ++;
}
if (toremove.length > 0){
    delete EventManager._listeners[listener];
    delete map[toremove[0]]
    count = count -1;
}
if(count == 0){
    delete EventManager._maps[type][srcid];
        delete EventManager._sources[src];
}

**Comment by jsutil4** [comment]
Seems that the EventManager._listeners is not necessary in function.

Besides, in removeEventListenerByType and removeAllEventListeners these two methods, the EventManager._listeners are not update accordingly, which may make the listener object can't be released.

**Comment by flashlizi** [comment]
yes, you are right, i will fix them.
